ddd

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -281,6 +281,27 @@ jobs:
           echo "${{ secrets.PRODUCTION_RSA_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
+      - name: SSH into VM, Deploy Backend
+        run: |
+          echo "SSHing into VM at ${{ secrets.PRODUCTION_VM_IP }}..."
+          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRODUCTION_VM_IP }} << EOF
+          echo "Checking for Node.js..."
+          if ! command -v node &> /dev/null; then
+          echo "Node.js not found. Installing Node.js..."
+           # This installs Node.js 20.x via NodeSource
+           curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
+           sudo apt-get install -y nodejs
+          else
+           echo "Node.js is installed."
+          fi
+
+          echo "Deploying the backend..."
+          cd code/one-roof/backend
+          git pull
+          npm install
+          npm run prod
+          echo "✅ Deployment completed."
+
       - name: SSH into VM & Backup MongoDB
         run: |
           echo "SSHing into VM at ${{ secrets.PRODUCTION_VM_IP }}..."
@@ -294,25 +315,6 @@ jobs:
               --authenticationMechanism=SCRAM-SHA-256 \
               --archive="/home/ubuntu/mongo_backups/backup_${TIMESTAMP}.archive" \
 
-      - name: SSH into VM, Deploy Backend
-        run: |
-          echo "SSHing into VM at ${{ secrets.PRODUCTION_VM_IP }}..."
-          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRODUCTION_VM_IP }} << EOF
-            echo "Checking for Node.js..."
-            if ! command -v node &> /dev/null; then
-             echo "Node.js not found. Installing Node.js..."
-              # This installs Node.js 20.x via NodeSource
-              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
-              sudo apt-get install -y nodejs
-            else
-              echo "Node.js is installed."
-            fi
-          
-            echo "Deploying the backend..."
-            cd code/one-roof/backend
-            git pull
-            npm install
-            npm run prod
-            echo "✅ Deployment completed."
+  
       
 
